"use client";
import Button from "@/components/button/Button";
import { useRouter } from "next/navigation";
import Head from "next/head";

const metadata = {
  title: "About page",
  description: "About page generated by beautiful me!",
};

const About = () => {
  const router = useRouter();
    <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
    </Head>

  const handleClick = () => router.push("/");
  return (
    <>
      <div>About</div>
      <Button
        handleClick={handleClick}
        text="Back to home"
        className="btn-nav"
      />
    </>
  );
};

export default About;
