import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation/Navigation";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
import {main} from './page.module.css'

export const metadata = {
  title: {
    default: 'Next 14 app Homepage',
    template: '%s | Next.JS 14'
  },
  description: "Generated by beautiful me!",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={main}>
        <Navigation />
        {children}
        <Footer />
        </body>
    </html>
  );
}
